# Generated by Django 4.2.13 on 2024-08-21 14:27

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='content',
            field=ckeditor.fields.RichTextField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='hero_description',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='hero_heading',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='hero_image',
            field=models.ImageField(default='default', upload_to='hero_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='mission_description',
            field=ckeditor.fields.RichTextField(default='default', validators=[django.core.validators.MaxLengthValidator(475)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='mission_image',
            field=models.ImageField(default='default', upload_to='mission_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='mission_title',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='skills',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='topservice',
            name='description',
            field=ckeditor.fields.RichTextField(validators=[django.core.validators.MaxLengthValidator(475)]),
        ),
        migrations.CreateModel(
            name='AccordionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accordion_items', to='main.service')),
            ],
        ),
    ]
