# Generated by Django 4.2.13 on 2024-08-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_service_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='skills',
            field=models.TextField(),
        ),
    ]
