# Generated by Django 4.2.13 on 2024-08-11 02:09

import ckeditor.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_service_hero_description_service_hero_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topservice',
            name='description',
            field=ckeditor.fields.RichTextField(validators=[django.core.validators.MaxLengthValidator(475)]),
        ),
    ]
