# Generated by Django 4.2.13 on 2024-08-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_topservice_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default="{% static 'main/img/icons8-salesforce-48.png' %}", upload_to='testimonial_images/'),
        ),
    ]
