# Generated by Django 4.2.13 on 2024-08-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_testimonial_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default='person.jpg', upload_to='testimonial_images/'),
        ),
    ]
