# Generated by Django 4.2.13 on 2024-08-11 07:14

import ckeditor.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_testimonial_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accordionitem',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='mission_description',
            field=ckeditor.fields.RichTextField(validators=[django.core.validators.MaxLengthValidator(475)]),
        ),
    ]
