# Generated by Django 4.2.13 on 2024-08-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_testimonial_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='hero_description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='hero_heading',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='hero_image',
            field=models.ImageField(default=' ', upload_to='hero_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(default=' ', upload_to='service_icons/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='mission_image',
            field=models.ImageField(default=' ', upload_to='mission_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='mission_title',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
